# Generated by Django 3.2.20 on 2023-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fghj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sdfddfbfd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgfgngn', models.CharField(max_length=100)),
            ],
        ),
    ]
